# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkding-cleaner" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "f286dc6b0c9bb7d4e88fd64d82c7bb201ff92400080186645a0da6de59f929ca"
      url "https://github.com/dakotahp/linkding-cleaner/releases/download/v#{version}/linkding-cleaner_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e7f07992b11424ccb2c08ba5640c50654818b894ad13236cb27a074a03f9bc5c"
      url "https://github.com/dakotahp/linkding-cleaner/releases/download/v#{version}/linkding-cleaner_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20ca970a833883877e4a3e0241613befd1bbed3e15c0c4e516aa2fc65dcfcbd9"
      url "https://github.com/dakotahp/linkding-cleaner/releases/download/v#{version}/linkding-cleaner_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "66301628e58bfe573380efad74f5623b4ed319bf675125618930e1814872e1f6"
      url "https://github.com/dakotahp/linkding-cleaner/releases/download/v#{version}/linkding-cleaner_linux_amd64.tar.gz"
    end
  end

  name "linkding-cleaner"
  desc "CLI tool to check and archive dead bookmarks in linkding"
  homepage "https://github.com/dakotahp/linkding-cleaner"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkding-cleaner"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkding-cleaner"]
    end
  end

  # No zap stanza required
end
